### ISSUE TITLE
Install Dependencies process doesn't work

### ISSUE THREAD

**Issue by miklosakos** [MadameMalady/My-Waydroid-Manager#10]
As the title says, the following errors are thrown at me when I try running the Install Dependencies process from "First-time Setup":
```
Installing Dependencies, please wait...
bash: line 2: hostname: command not found
bash: line 2: [: =: unary operator expected
bash: line 7: hostname: command not found
bash: line 7: [: =: unary operator expected
bash: line 12: hostname: command not found
bash: line 12: [: =: unary operator expected
bash: line 16: hostname: command not found
bash: line 16: [: =: unary operator expected
Error 404
```
Distro is Arch Linux ARM by Danctnix from 2023-09-25.

**Comment by MadameMalady** [comment]
Not a supported distro, sorry.
Please don't open issues for distros that aren't supported, if you'd like to assist, you're welcome to make a pull request with the requested improvements.

**Comment by MadameMalady** [comment]
Not a supported distro, sorry.
Please don't open issues for distros that aren't supported, if you'd like to assist, you're welcome to make a pull request with the requested improvements.
