### ISSUE TITLE
Build the UI via Blueprint

### ISSUE THREAD

**Issue by orowith2os** [MadameMalady/My-Waydroid-Manager#5]
In your development goals, you stated that you have no plans to build the UI via XML. Why not use Blueprint instead?

It's good to have a clean separation of where the GUI and internal logic is handled, and dedicated .ui/.blp files are the standard way to do that with GTK.

**Comment by MadameMalady** [comment]
Right now, i'm pretty sure Blueprint only supports Vala (right..?), and I'm still learning Python..
Eventually, I do want to learn xml and make the ui that way for translation files, but for right now, I don't have the needed coding knowledge.

**Comment by orowith2os** [comment]
I've seen Blueprint used in Python and Rust projects, it's not limited to Vala. If I understand it correctly, you just need to replace every instance of an xml file with a blp file.

**Comment by MadameMalady** [comment]
Ahh, I misunderstood what Blueprint was, it's something I can check out at some point, and see if it would be easy enough to learn it, for now i'm going to continue defining the ui in the main executable, once all the main functions are finished, I'll revisit it, for now i'll close this till i've had a chance to look at and consider Blueprint.
