### ISSUE TITLE
Do not expect scripts to be in ~/MyWaydroidManager/scripts

### ISSUE THREAD

**Issue by TheKrafter** [MadameMalady/My-Waydroid-Manager#9]
When trying to install dependencies, a FileNotFoundError exception is raised because on line 300 the scripts are assumed to be in ~/MyWaydroidManager/scripts

https://github.com/MadameMalady/My-Waydroid-Manager/blob/da6ad9b62ebb67ade3e7735034c91daabe97c762/My%20Waydroid%20Manager/My_Waydroid_Manager.py#L300

They should be assumed to be in ./scripts/ by default and have some kind of env var, config, or command line arg to change that.

**Comment by MadameMalady** [comment]
scripts are going to be redundant in the next update, and that will be fixed.

**Comment by MadameMalady** [comment]
Also in the contribution guidelines, it does state I'm not a sr dev and I don't know everything, I don't fully understand your request, but I know it isn't needed with the next update.
In the future, feel free to instead make a pull request with your suggested improvements, and clear accompanying notations.
Thanks for your interest, this will be closed as completed now.
